import os
import shutil
import time, datetime
import tabulate

times = []
tests = [
    "taskBMC12_sodor5_itype", "taskBMC12_sodor5_ilstype", "taskBMC12_sodor5_rtype", "taskBMC15_sodor5_itype", "taskBMC15_sodor5_ilstype", "taskBMC15_sodor5_rtype"
]

for test in tests:
    print("Running test: " + test)
    
    # Test for equivalence
    pretime = time.time()
    os.system(f"time sby -f equiv.sby {test}")
    posttime = time.time()
    equiv_time = posttime - pretime
    print(f"For test: {test}, time: {equiv_time}")

    # Save the times
    times.append([
        test, equiv_time
    ])



with open("times.log", 'w') as f:
    f.write("// Generated by run_all.py at {}\n\n\n".format(datetime.datetime.now()))

    table = tabulate.tabulate(times, headers=["Test", "Equiv Time"])
    f.write(table)