import os
import shutil
import time, datetime
import tabulate

times = []
tests = [
    "taskBMC30_equiv_tlb", "taskBMC30_equiv_su", "taskBMC30_equiv_lsu"
]

for (i, test) in enumerate(tests):
    print("Running test: " + test)
    
    # Test equivalence
    pretime = time.time()
    os.system(f"time sby -f equiv.sby {test}")
    posttime = time.time()
    equiv_time = posttime - pretime
    print(f"For test: {test} DUT time: {equiv_time}")

    # Save the times
    times.append([
        test, equiv_time
    ])



with open("times.log", 'w') as f:
    f.write("// Generated by run_all.py at {}\n\n\n".format(datetime.datetime.now()))

    table = tabulate.tabulate(times, headers=["Test", "Equiv time"])
    f.write(table)